In [2]:
import torch

a = torch.tensor([1,2,3,4])

print(a[None])

tensor([[1, 2, 3, 4]])


In [3]:
a.unsqueeze(1)
print(a)

tensor([1, 2, 3, 4])


In [18]:
sid = range(8)
parse = torch.tensor([1,2,3,4])
print(parse)
for id in sid:
    mask =  (parse == id).float()
    print(mask.data)

tensor([1, 2, 3, 4])
tensor([0., 0., 0., 0.])
tensor([1., 0., 0., 0.])
tensor([0., 1., 0., 0.])
tensor([0., 0., 1., 0.])
tensor([0., 0., 0., 1.])
tensor([0., 0., 0., 0.])
tensor([0., 0., 0., 0.])
tensor([0., 0., 0., 0.])


In [21]:
from torchvision import transforms
 
toPIL = transforms.ToPILImage() #这个函数可以将张量转为PIL图片，由小数转为0-255之间的像素值
img = torch.randn(3,512,372)
pic = toPIL(img)
pic.save('random.jpg')